# Generated by Django 4.2 on 2024-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_actor_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel'), ('dark', 'Dark')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
