# Generated by Django 4.2 on 2024-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approved',
        ),
        migrations.AddField(
            model_name='adminrequestmessage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
